name: Delete Pull Request environment

on:
  pull_request:
    types: [closed]

jobs:
  delete-pr-environment:
    name: Delete Pull Request environment
    uses: uug-ai/workflows/.github/workflows/pr-delete-environment.yml@main
    with:
      action: ${{ github.event.action }}
      project: ${{ github.event.repository.name }}
      pr_number: ${{ github.event.number }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
