name: Update Pull Request environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-pr-environment:
    name: Update Pull Request environment
    uses: uug-ai/workflows/.github/workflows/pr-update-environment.yml@main
    with:
      action: ${{ github.event.action }}
      organization: uug-ai
      project: ${{ github.event.repository.name }}
      pr_number: ${{ github.event.number }}
      sha: ${{ github.sha }}
      tag: ${{ github.event.repository.name }}-pr${{ github.event.number }}-${{ github.sha }}
      docker_context: .
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}
